- app/Http/Controllers/AgendaItemController.php
Deze pr fixed de verkeerd getoonde flash bericht bij het update van een agenda item
> Wrong flash message

- app/Http/Controllers/CertificateController.php
- app/Http/Controllers/UserCertificateController.php
- app/Http/Controllers/UserController.php
- config/constants.php
- database/seeds/RolTableSeeder.php
- resources/views/beheer/user/index.blade.php
- resources/views/beheer/user/show.blade.php
- resources/views/layouts/beheer.blade.php
Fixes #21 
Zou iemand goed kunnen checken of de "cert admin" role niet te uitgebreide permissies heeft?
> Added certificate admin role 

- app/Http/Controllers/frontEndController.php
- resources/lang/en/front-end/news.php
- resources/lang/nl/front-end/news.php
- resources/views/front-end/agenda_detail.blade.php
- resources/views/front-end/news.blade.php
- resources/views/front-end/news_detail.blade.php
- routes/web.php
> News update

- app/Http/Controllers/NewsItemController.php
- app/NewsItem.php
- app/repositories/NewsItemRepository.php
- database/migrations/2018_11_25_131633_add_custom_author_field_to_news_items.php
- database/migrations/2018_11_25_131903_migrate_created_by_field_author_field.php
- database/migrations/2018_11_25_132053_remove_created_by_field_from_news_items_table.php
- database/seeds/newsItemSeeder.php
- package-lock.json
- resources/lang/en/NewsItem.php
- resources/lang/nl/NewsItem.php
- resources/views/beheer/newsItem/create_edit.blade.php
- resources/views/beheer/newsItem/index.blade.php
- resources/views/beheer/newsItem/show.blade.php
- resources/views/front-end/home.blade.php
- resources/views/front-end/news.blade.php
- resources/views/front-end/news_detail.blade.php
De auteur veld bij een nieuws item in nu een text veld geworden inplaats de gebruiker die het aanmaakt. #32
> Nieuws auteur veld is vrij invulbaar

- resources/lang/en/menu.php
- resources/lang/nl/menu.php
- resources/views/beheer/user/show.blade.php
- resources/views/front-end/subscribe.blade.php
- resources/views/includes/menu.blade.php
Fixes:
#40, #36, #39 
En een extra vertaling toegevoegd aan het menu.
> Multiple fixes

- app/Http/Controllers/Api/AgendaController.php
- resources/views/beheer/agendaItem/index.blade.php
Momenteel wordt de link naar de inschrijving niet meer getoond in de lijst met agenda item in het beheer stuk. Dit pull reqeust lost dit probleem op
> Link naar inschrijvingen tonen

- app/MenuItem.php
- resources/views/includes/menu.blade.php
> All menu items links are shown in the menu

- readme.md
- resources/views/front-end/agenda.blade.php
fixed typo in comment
updated readme to include fix for loading agenda/zekeringen for local development
> updated readme with fix for api port

- resources/views/beheer/user/show.blade.php
Fixes #75 
In de oude situatie werd altijd het eerste certificate verwijderd. Dit lost dat op.
> Fixed certificate removal

- app/MenuItem.php
> Submenu items that are made invisibile in the menu were still visible

- app/Http/Controllers/ManageController.php
- resources/lang/en/menu.php
- resources/lang/en/user.php
- resources/lang/nl/menu.php
- resources/lang/nl/user.php
- resources/views/beheer/user/index.blade.php
- resources/views/layouts/beheer.blade.php
Fixes #33 
Ik heb net gecheckt of alle menu items nog kloppen met de rollen, maar zouden jullie dat ook kunnen doen? Enige wijziging is dat activity beheerders geen nieuws items meer aan kunnen maken.
In de managecontroller heb ik ook de compact('menu')  weg gehaald, dit komt omdat ik lokaal php7.3 draai.
> Fixed the manage sidebar on smaller screens and mobile devices

- resources/assets/js/photoAlbum.js
Kon geen `npm run production` runnen op de server door syntax errors in photoAlbum.js, heb het door een linter gehaald en toen haalde ik er een paar syntax errors uit.
> Hotfix for photoAlbum.js due to syntax errors

- database/migrations/2018_11_25_132053_remove_created_by_field_from_news_items_table.php
Fixed an issues in the down methode of the remove createdBy migration #84
> Migration fix

- app/Http/Controllers/Api/AgendaController.php
The agenda filters now correctly on category #86
> Fixed agenda filter

- app/User.php
When a user is set as inactive the roles are now removed. #77
> remove roles from inactive users

- resources/views/beheer/agendaItem/create_edit_image.blade.php
Agenda items konden niet meer worden aangemaakt, nu weer wel.
> Fixed agenda creation bug

- app/Http/Controllers/NewsItemController.php
- resources/assets/vue/components/agenda/Agenda.vue
- resources/lang/en/front-end/agenda.php
- resources/lang/nl/front-end/agenda.php
- resources/views/front-end/agenda.blade.php
- resources/views/front-end/photo_album_list.blade.php
Voegt een export knop toe aan de agenda pagina.
> Agenda export button

- app/Http/Controllers/SettingsController.php
- app/Providers/AppServiceProvider.php
- app/Setting.php
- database/migrations/2019_04_20_080732_create_settings_table.php
- database/migrations/2019_04_20_083716_add_blocked_email_domain_setting.php
- resources/lang/en/settings.php
- resources/lang/nl/settings.php
- resources/views/beheer/settings/edit.blade.php
- resources/views/beheer/settings/index.blade.php
- resources/views/layouts/beheer.blade.php
- routes/web.php
Er is een settings page toegevoegd met nu een setting om top domain email adress op te geven die geblokeerd moeten worden.
Het blokeren van de email is nog niet ingebouwt.
> Added settings page

- package-lock.json
- package.json
> Upgrade jqeury to 3.4.1

- resources/assets/js/datatables.js
- resources/views/beheer/agendaItem/index.blade.php
- resources/views/beheer/newsItem/index.blade.php
- webpack.mix.js
> Fixed sorting dates in datatables

- app/Http/Controllers/PendingUserController.php
- app/Http/Controllers/UserController.php
- app/Rules/EmailDomainValidator.php
- resources/lang/en/validation.php
- resources/lang/nl/validation.php
School emails that are set in the setting are now blocked. #101
> Added check to block school emails

- app/AgendaItem.php
- app/repositories/AgendaItemRepository.php
- app/repositories/InschrijvenRepository.php
- database/migrations/2019_05_14_183925_add_climbing_activity_to_agenda_item_table.php
- resources/lang/en/AgendaItems.php
- resources/lang/nl/AgendaItems.php
- resources/views/beheer/agendaItem/create_edit_default_info.blade.php
- resources/views/beheer/agendaItem/show.blade.php
Now when making an agenda item you can selected if it is a climbing activity. 
If it is a climbing activity we show the certificates for the user in the agenda detail page.
#43
> Climbing certificates are only shown for climbing activties

- resources/lang/en/AgendaItems.php
- resources/lang/nl/AgendaItems.php
- resources/views/beheer/agendaItem/create_edit_default_info.blade.php
Changed text and the checkbox is now not always check in the edit screen #141
> fixed show climbing certificates ceckbox

- composer.lock
- package-lock.json
- tests/Browser/LanguageTest.php
php webdriver is geupdate en nu werkt dusk weer.
> Update dependencies and enabled lang test after dusk update

- app/Http/Controllers/UserController.php
- app/User.php
- resources/lang/en/user.php
- resources/lang/nl/user.php
- resources/views/beheer/user/show.blade.php
- routes/web.php
- tests/Feature/User/MakeUserActiveTest.php
> Add make user active button

- app/Book.php
- app/Http/Controllers/LibraryController.php
- app/Http/Controllers/frontEndController.php
- database/migrations/2019_11_24_151650_add_code_to_library.php
- database/seeds/BooksTableSeeder.php
- resources/lang/en/book.php
- resources/lang/nl/book.php
- resources/views/beheer/book/create_edit.blade.php
- resources/views/beheer/book/index.blade.php
- resources/views/beheer/book/show.blade.php
- resources/views/front-end/library.blade.php
Elke boek heeft een code, dit kan nu ook op de website ingevoerd worden.
> Add code to book

- app/Http/Controllers/PhotoAlbumController.php
- app/Http/Controllers/PhotoController.php
- app/Http/Controllers/frontEndController.php
- app/PhotoAlbum.php
- app/repositories/PhotoAlbumRepository.php
- database/migrations/2019_11_24_200556_add_softdelete.php
- resources/lang/en/menu.php
- resources/lang/en/photoAlbum.php
- resources/lang/nl/menu.php
- resources/lang/nl/photoAlbum.php
- resources/views/beheer/photoAlbum/create_edit.blade.php
- resources/views/beheer/photoAlbum/index.blade.php
- resources/views/beheer/photoAlbum/show.blade.php
- resources/views/layouts/beheer.blade.php
- routes/web.php
> Adds delete and update to beheer for photoalbums

- .travis.yml
- deploy.sh
- install.sh
- lighthouserc.json
- package-lock.json
- package.json
integratie met lighthouse
Ik heb een lighthouse server opgezet die de data bijhoud, dit was niet nodig geweest want je kunt ook tijdelijke analyses opslaan op de google cloud, maar het leek me leuk om een goed overzicht te hebben van alle branches. 
Elke keer als er een deployment gedaan word naar de staging server word deze getest en komt die op de ligthouse ci server terecht http://beta.esac.nl:9001/app/projects/beta.esac.nl en word er een status toegevoegd aan de PR op github.
Vooralsnog zitten er geen audits aan, dit betekend dat hij alles goedkeurd, we kunnen dit in de toekomst wel doen om het duidelijker te maken dat een change een effect heeft om de performance van de website.
Voor een voorbeeld rapport: http://beta.esac.nl:9001/app/projects/beta.esac.nl/compare/9c9dd362e1b5 klik …
> Lighthouse integration

- deploy.sh
fixed key logic
nu zou die moeten kunnen deployen naar prod
> update key logic

- app/Http/Controllers/InschrijfController.php
> Sanitize filename of agenda export

- Dockerfile
- app/Http/Controllers/ApiController.php
- app/Http/Controllers/MailListController.php
- install.sh
- resources/lang/en/MailList.php
- resources/lang/nl/MailList.php
- resources/views/beheer/mailList/adduser.blade.php
- resources/views/beheer/mailList/show.blade.php
Inplaats van lid voor lid kunnen nu meerdere leden tegelijk aan de maillijst toegevoegd worden
> Multiple members can be added to mail list in one go

- config/session.php
> Increase session lifetime default and set samesite attribute

- composer.lock
- package-lock.json
- resources/lang/en/kind_of_member.php
- resources/lang/nl/kind_of_member.php
- resources/views/front-end/subscribe.blade.php
> Update deps and fix extraordinary participant and singup country

- app/Http/Controllers/ApiController.php
- resources/views/beheer/mailList/adduser.blade.php
- resources/views/beheer/mailList/show.blade.php
> Removes pending users from maillist add and bug in adding multiple users

- app/Exports/LibraryExport.php
- app/Http/Controllers/LibraryController.php
- resources/views/beheer/book/index.blade.php
- resources/views/beheer/user/index.blade.php
- routes/web.php
Added an export library function to download the entire esac library overview in an excel file.
> Export books

- resources/views/layouts/master.blade.php
Code to allow a rough version of changing the website layout based on unix timestamps.
Has one preset event, for a temporary change of approximatley 14 hours.
> Added time based layout changes.
